version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - nvm install
  build:
    commands:
      - npm test
      - npm run sls -- deploy -s $STAGE -r $REGION
      - npm run acceptance
